### ISSUE TITLE
Loading a second metadata file does weird things

### ISSUE THREAD

**Issue by Susurrus** [xela144/CANaconda#70]
I've had problems with this, confirm it works properly. Especially what should/does happen if the 2nd metadata file parses incorrectly. Those edge cases need to be handled.

**Comment by xela144** [comment]
Can you elaborate? I just tried and it works.

The only bug is that the second time you load the metadata, the dialog window goes to the background (on ubuntu). This is because the dialog window code is a ![one-liner](https://github.com/xela144/CANaconda/blob/3e5827740124d7bced1be8406633c35313e0119a/canaconda_GUI.py#L296).

**Comment by Susurrus** [comment]
I think what happened is that I loaded a second metadata file which failed to parse. So in that case the application was left in a weird state because it didn't fully load the second file.

**Comment by Susurrus** [comment]
This is definitely possible for user-created XML files as well, so this should be fixed by 1.0

**Comment by xela144** [comment]
Alright, I'll try to replicate this.

**Comment by xela144** [comment]
Tried this:
Load 'AllMessage.xml' and begin streaming.
Load 'badMetdata.xml'. The old XML file is still visible in the Metadata tab, but the program cannot parse any messages. 

So we need to find a way to clear the Metadata tab when a bad file is loaded, or not load the bad file and just keep the old one.

**Comment by xela144** [comment]
b7b2431a57b8c99f9a501a1b43a1ed1eb9d2ad11
